- hosts: localhost
  become: true
  tasks:
    - name: Install emacs
      apt: 
        name: emacs
    - name: Get updated files from git repository
      git:
        repo: https://{{ githubusername | urlencode }}:{{ githubpassword | urlencode }}@github.com/ansibleHW.git
        dest: /tmp
  #vars_prompt:
  #  - name: "githubusername"
  #    prompt: "Enter your github username"
  #    private: no
  #  - name: "githubpassword"
  #    prompt: "Enter your github password"
  #    private: yes
